import type { Aluguel } from "@/domain/tipos";

/**
 * Dados fictícios para a primeira tela enquanto o schema Jazz não está
 * conectado. Removidos quando entrar a camada de persistência (sessão 2).
 */
export const MOCK_ALUGUEIS: Aluguel[] = [
  {
    id: "alg-001",
    clienteId: "cli-001",
    clienteNome: "Maria Aparecida Silva",
    local: "Salão Buritis · Centro",
    dataEntrega: new Date(2026, 4, 12),
    dataRetirada: new Date(2026, 4, 13),
    tipo: "Dourada",
    quantidade: 80,
    valorUnitario: 10,
    pago: 800,
    status: "Confirmado",
    criadoEm: new Date(2026, 4, 1),
    atualizadoEm: new Date(2026, 4, 1),
  },
  {
    id: "alg-002",
    clienteId: "cli-002",
    clienteNome: "João Carlos Pereira",
    local: "Sítio Recanto Verde",
    dataEntrega: new Date(2026, 4, 15),
    dataRetirada: new Date(2026, 4, 16),
    tipo: "Imbúia",
    quantidade: 120,
    valorUnitario: 12,
    pago: 720,
    status: "Postergado",
    criadoEm: new Date(2026, 3, 28),
    atualizadoEm: new Date(2026, 4, 5),
  },
  {
    id: "alg-003",
    clienteId: "cli-003",
    clienteNome: "Lúcia Helena Santos",
    local: "Igreja N. S. da Paz",
    dataEntrega: new Date(2026, 4, 18),
    dataRetirada: new Date(2026, 4, 18),
    tipo: "Cristal",
    quantidade: 60,
    valorUnitario: 12,
    pago: 800,
    status: "Confirmado",
    observacao: "Cliente pagou a mais; saldo a favor",
    criadoEm: new Date(2026, 4, 2),
    atualizadoEm: new Date(2026, 4, 2),
  },
  {
    id: "alg-004",
    clienteId: "cli-004",
    clienteNome: "Roberto Mendes",
    local: "Buffet Estrela do Norte",
    dataEntrega: new Date(2026, 4, 2),
    dataRetirada: new Date(2026, 4, 3),
    tipo: "Âmbar",
    quantidade: 100,
    valorUnitario: 13,
    pago: 1300,
    status: "Encerrado",
    criadoEm: new Date(2026, 3, 15),
    atualizadoEm: new Date(2026, 4, 4),
  },
  {
    id: "alg-005",
    clienteId: "cli-005",
    clienteNome: "Patrícia Oliveira",
    local: "Clube Atlético Municipal",
    dataEntrega: new Date(2026, 4, 25),
    dataRetirada: new Date(2026, 4, 25),
    tipo: "Dourada",
    quantidade: 200,
    valorUnitario: 12,
    pago: 1200,
    status: "Cancelado",
    criadoEm: new Date(2026, 3, 30),
    atualizadoEm: new Date(2026, 4, 6),
  },
];
